<table class="table table-condensed">
  <tr>
    <th><?=$this->transEsc('Location')?></th>
    <th><?=$this->transEsc('Call Number')?></th>
    <th><?=$this->transEsc('Status')?></th>
  </tr>
  <? $i = 0; foreach ($this->statusItems as $item): ?>
    <? if (++$i == 3) break; // Show no more than 5 items ?>
    <tr>
      <td><?=$this->escapeHtml($item['location'])?></td>
      <td>
<? if ($item['location']!=='Internet Resource'): ?>
	  <?=$this->escapeHtml($item['callnumber'])?>
	          <? endif; ?>
	  </td>
      <td>
        <? if (isset($item['use_unknown_message']) && $item['use_unknown_message']): ?>
          <span><?=$this->transEsc("status_unknown_message")?></span>
        <? elseif ($item['availability']): ?>
         <? if ($item['location']!=='Internet Resource'): ?>
          <span class="text-success"><?=($item['reserve'] == 'Y') ? $this->transEsc("On Reserve") : $this->transEsc("Available")?></span>
         <? elseif ($item['location']=='Internet Resource'): ?>
          <span class="text-success"><?=$this->transEsc("Online")?></span>
	          <? endif; ?>
        <? else: ?>
         <? if ($item['status']=='Charged'): ?> 
           <span class="text-danger"><?=$this->transEsc("Charged")?></span>
         <? elseif ($item['status']=='Renewed'): ?> 
           <span class="text-danger"><?=$this->transEsc("Charged")?></span>
         <? elseif ($item['status']=='Overdue'): ?> 
           <span class="text-danger"><?=$this->transEsc("Overdue")?></span>
		<? else: ?>
         			<span class="text-danger"><?=$this->transEsc($item['status'])?></span>
        <? endif; ?>
        <? endif; ?>
      </td>
    </tr>
  <? endforeach; ?>
<? if (count($this->statusItems) > 3): ?>
  <tr><td colspan="3"><a href="<?=$this->url('record', array('id' => $this->statusItems[0]['id']))?>"><?=count($this->statusItems) - 2?> <?=$this->transEsc('more')?> ...</a></td></tr>
<? endif; ?>
</table>
