</div>
<div class="form-group">
  <label class="col-sm-2 control-label" for="login_password"><?=$this->transEsc('Last Name')?>:</label>
  <div class="col-sm-10">
    <input type="text" name="password" id="login_password" class="form-control"/>
  </div>
</div>

<div class="form-group">
  <label class="col-sm-2 control-label" for="login_username"><?=$this->transEsc('855 Number')?>:</label>
  <div class="col-sm-10">
    <input type="password" name="username" id="login_username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control"/>
  </div>
